### ISSUE TITLE
gulp default task fails

### ISSUE THREAD

**Issue by staltz** [ivan-kleshnin/cyclejs-examples#3]
I cloned the repo, did `npm install`, then ran `gulp` and I got this error:

```
$ gulp
[gulp] Using gulpfile ./gulpfile.js
[gulp] Starting 'default'...
[gulp] Starting 'dist-html'...
[gulp] Starting 'dist-css'...
[gulp] Starting 'dist-less'...
[gulp] Finished 'dist-less' after 84 μs
[gulp] Finished 'default' after 13 ms
[gulp] Finished 'dist-css' after 63 ms
[gulp] Finished 'dist-html' after 73 ms
[gulp] Starting 'build'...
[gulp] Finished 'build' after 226 ms
[gulp] Starting 'bundle-vendors'...
[gulp] Finished 'bundle-vendors' after 5.65 ms
[gulp] Starting 'prebundle-apps'...
[gulp] Finished 'prebundle-apps' after 15 ms
[gulp] Starting 'bundle-apps'...
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at WriteStream.EventEmitter.once (events.js:185:8)
    at Socket.Readable.pipe (_stream_readable.js:541:8)
    at ./gulpfile.js:97:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at WriteStream.EventEmitter.once (events.js:185:8)
    at Socket.Readable.pipe (_stream_readable.js:541:8)
    at ./gulpfile.js:98:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at Socket.Readable.pipe (_stream_readable.js:476:8)
    at ./gulpfile.js:97:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at ./node_modules/gulp/node_modules/orchestrator/index.js:279:18
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at Socket.Readable.pipe (_stream_readable.js:491:8)
    at ./gulpfile.js:97:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at ./node_modules/gulp/node_modules/orchestrator/index.js:279:18
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at WriteStream.EventEmitter.once (events.js:185:8)
    at Socket.Readable.pipe (_stream_readable.js:536:8)
    at ./gulpfile.js:97:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at Socket.Readable.pipe (_stream_readable.js:476:8)
    at ./gulpfile.js:98:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at ./node_modules/gulp/node_modules/orchestrator/index.js:279:18
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at Socket.Readable.pipe (_stream_readable.js:491:8)
    at ./gulpfile.js:98:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at ./node_modules/gulp/node_modules/orchestrator/index.js:279:18
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.EventEmitter.addListener (events.js:160:15)
    at WriteStream.Readable.on (_stream_readable.js:689:33)
    at WriteStream.EventEmitter.once (events.js:185:8)
    at Socket.Readable.pipe (_stream_readable.js:536:8)
    at ./gulpfile.js:98:20
    at Array.forEach (native)
    at Gulp.<anonymous> (./gulpfile.js:89:8)
    at module.exports (./node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (./node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (./node_modules/gulp/node_modules/orchestrator/index.js:214:10)
[gulp] Finished 'bundle-apps' after 62 ms
[gulp] Starting 'watch-src'...
[gulp] Finished 'watch-src' after 55 ms
[gulp] Starting 'watch-build'...
[gulp] Finished 'watch-build' after 23 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by ivan-kleshnin** [comment]
I think this line `require("events").EventEmitter.defaultMaxListeners = 999;` in `gulpfile.js` does not work until node@0.12 To workaround you may remove all `src/<app>` except the one you want to test.
Than, the number of spawned processes will be within the default limit (11). I plan to restructure project folders but for now that's how it is :(

Also, it's required to run `$ bin/fixes/globule` to prevent gulp/vinyl-fs/globule bug.

**Comment by ivan-kleshnin** [comment]
@jdalton promises to fix this annoying relic
https://github.com/babel/babel/issues/489
It's awful how long it takes

**Comment by jdalton** [comment]
~~I'll try to tackle it soon. Finishing up the 3.6.0 release at the moment.~~ [Fixed](https://github.com/babel/babel/issues/489#issuecomment-87736017).
